# Generated by Django 2.0 on 2018-02-15 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(db_column='week')),
                ('type', models.CharField(db_column='type', max_length=45, null=True)),
                ('comments', models.TextField(blank=True, db_column='comments', null=True)),
                ('time', models.DateTimeField(db_column='time', null=True)),
                ('recipe', models.ForeignKey(db_column='recipe', on_delete=django.db.models.deletion.PROTECT, to='recipes.Recipe')),
            ],
            options={
                'db_table': 'home',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(db_column='recipe', on_delete=django.db.models.deletion.PROTECT, to='recipes.Recipe')),
                ('week', models.ForeignKey(db_column='week', on_delete=django.db.models.deletion.PROTECT, to='home.Home')),
            ],
            options={
                'db_table': 'pick',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='pick',
            unique_together={('week', 'recipe')},
        ),
        migrations.AlterUniqueTogether(
            name='home',
            unique_together={('week', 'recipe')},
        ),
    ]
