# Generated by Django 2.0 on 2018-02-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='instructions',
        ),
        migrations.AddField(
            model_name='recipe',
            name='directions',
            field=models.TextField(db_column='directions', null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(db_column='name', max_length=200, null=True),
        ),
    ]
